services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ctfmap
      POSTGRES_PASSWORD: ctfmap
      POSTGRES_DB: ctfmap
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  api:
    build: .
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://ctfmap:ctfmap@db:5432/ctfmap
      DATABASE_URL_SYNC: postgresql+psycopg2://ctfmap:ctfmap@db:5432/ctfmap
    depends_on:
      - db
    networks:
      - internal
      - external


networks:
  internal:

  external:
    driver: bridge

volumes:
  pgdata:
