import { useEffect, useState } from 'react';
import * as eventsApi from '../../api/eventsApi';
import { InlineNotice, LoadingPanel, PageHeader } from '../../components/AdminUi';
import { StatusIndicator } from '../../components/StatusIndicator';
import type { AdminEvent, ApiError, EventUpdate } from '../../types/admin';

export function EventEditPage({ id, onNavigate }: { id: string; onNavigate: (path: string) => void }) {
  const [event, setEvent] = useState<AdminEvent | null>(null); const [form, setForm] = useState<EventUpdate | null>(null); const [loading, setLoading] = useState(false); const [cancelling, setCancelling] = useState(false); const [confirmCancel, setConfirmCancel] = useState(false); const [notice, setNotice] = useState<{ kind: 'success' | 'error'; text: string } | null>(null);
  useEffect(() => { void eventsApi.get(id).then((item) => { setEvent(item); setForm({ title: item.title, description: item.description, url: item.url, organizer: item.organizer, format: item.format, difficulty: item.difficulty, startDate: item.startDate, endDate: item.endDate, city: item.city, region: item.regionId, lat: item.lat ?? 0, lng: item.lng ?? 0, tags: item.tags.join(', ') }); }).catch(() => onNavigate('/404')); }, [id, onNavigate]);
  const set = <K extends keyof EventUpdate>(key: K, value: EventUpdate[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!form) return; setLoading(true); setNotice(null); try { const updated = await eventsApi.update(id, form); setEvent(updated); setNotice({ kind: 'success', text: 'Изменения в карточке соревнования сохранены.' }); } catch (reason) { setNotice({ kind: 'error', text: (reason as ApiError).message || 'Не удалось сохранить данные.' }); } finally { setLoading(false); } };
  const cancelEvent = async () => { setCancelling(true); setNotice(null); try { const updated = await eventsApi.cancel(id); setEvent(updated); setConfirmCancel(false); setNotice({ kind: 'success', text: 'Соревнование отменено и удалено с публичной карты.' }); } catch (reason) { setNotice({ kind: 'error', text: (reason as ApiError).message || 'Не удалось отменить соревнование.' }); } finally { setCancelling(false); } };
  if (!event || !form) return <LoadingPanel label="ЗАГРУЗКА СОРЕВНОВАНИЯ" />;
  return <><PageHeader code={`АДМИНИСТРАТОР / СОРЕВНОВАНИЯ / ${event.id.toUpperCase()}`} title="Редактирование соревнования" description="Изменение оперативных данных соревнования." actions={<StatusIndicator status={event.status} />} />
    <form className="edit-form" onSubmit={save}>{notice && <InlineNotice kind={notice.kind}>{notice.text}</InlineNotice>}
      {confirmCancel && <div className="confirmation-panel" role="alertdialog" aria-modal="true" aria-labelledby="cancel-event-title"><p className="panel-code">ОТМЕНА СОРЕВНОВАНИЯ</p><h2 id="cancel-event-title">Отменить активное соревнование?</h2><p>Соревнование будет снято с публикации и его флажок исчезнет с карты.</p><div><button type="button" className="button admin-button" onClick={() => setConfirmCancel(false)}>НЕТ, ОСТАВИТЬ</button><button type="button" className="button admin-button admin-button--reject" disabled={cancelling} onClick={() => void cancelEvent()}>{cancelling ? 'ОТМЕНА...' : 'ДА, ОТМЕНИТЬ'}</button></div></div>}
      <FormSection code="01" title="Основные сведения"><Field label="НАЗВАНИЕ СОРЕВНОВАНИЯ"><input value={form.title} onChange={(e) => set('title', e.target.value)} required /></Field><Field label="ОРГАНИЗАТОР"><input value={form.organizer} onChange={(e) => set('organizer', e.target.value)} required /></Field><Field label="ОПИСАНИЕ" wide><textarea rows={4} value={form.description} onChange={(e) => set('description', e.target.value)} required /></Field></FormSection>
      <FormSection code="02" title="Место проведения"><Field label="ГОРОД"><input value={form.city} onChange={(e) => set('city', e.target.value)} /></Field><Field label="КОД РЕГИОНА"><input value={form.region} onChange={(e) => set('region', e.target.value)} /></Field><Field label="ШИРОТА"><input type="number" step="any" value={form.lat} onChange={(e) => set('lat', Number(e.target.value))} /></Field><Field label="ДОЛГОТА"><input type="number" step="any" value={form.lng} onChange={(e) => set('lng', Number(e.target.value))} /></Field></FormSection>
      <FormSection code="03" title="Расписание и классификация"><Field label="ДАТА НАЧАЛА"><input type="date" value={form.startDate} onChange={(e) => set('startDate', e.target.value)} /></Field><Field label="ДАТА ЗАВЕРШЕНИЯ"><input type="date" value={form.endDate} onChange={(e) => set('endDate', e.target.value)} /></Field><Field label="ФОРМАТ"><select value={form.format} onChange={(e) => set('format', e.target.value as EventUpdate['format'])}><option value="online">ОНЛАЙН</option><option value="offline">ОЧНО</option><option value="hybrid">ГИБРИД</option></select></Field><Field label="СЛОЖНОСТЬ"><select value={form.difficulty} onChange={(e) => set('difficulty', e.target.value as EventUpdate['difficulty'])}><option>Начальный</option><option>Средний</option><option>Высокий</option><option>Экспертный</option></select></Field></FormSection>
      <FormSection code="04" title="Внешние ссылки"><Field label="ОФИЦИАЛЬНАЯ ССЫЛКА"><input type="url" value={form.url} onChange={(e) => set('url', e.target.value)} /></Field><Field label="МЕТКИ"><input value={form.tags} onChange={(e) => set('tags', e.target.value)} placeholder="Веб, бинарная эксплуатация, командное" /></Field></FormSection>
      <footer className="form-actions">{event.status === 'active' && <button type="button" className="button admin-button admin-button--reject" onClick={() => setConfirmCancel(true)}>ОТМЕНИТЬ СОРЕВНОВАНИЕ</button>}<button type="button" className="button admin-button" onClick={() => onNavigate('/admin/events')}>НАЗАД</button><button className="button admin-button admin-button--primary" disabled={loading || event.status !== 'active'}>{loading ? 'СОХРАНЕНИЕ...' : 'СОХРАНИТЬ ИЗМЕНЕНИЯ'} →</button></footer>
    </form></>;
}
function FormSection({ code, title, children }: { code: string; title: string; children: React.ReactNode }) { return <section className="form-section"><header><span>{code}</span><h2>{title}</h2></header><div className="form-grid">{children}</div></section>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`field ${wide ? 'field--wide' : ''}`}><span>{label}</span>{children}</label>; }
