import { useEffect, useState } from 'react';
import * as eventsApi from '../../api/eventsApi';
import { InlineNotice, LoadingPanel, PageHeader } from '../../components/AdminUi';
import { StatusIndicator } from '../../components/StatusIndicator';
import type { AdminEvent, ApiError, EventUpdate } from '../../types/admin';

export function EventEditPage({ id, onNavigate }: { id: string; onNavigate: (path: string) => void }) {
  const [event, setEvent] = useState<AdminEvent | null>(null); const [form, setForm] = useState<EventUpdate | null>(null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState<{ kind: 'success' | 'error'; text: string } | null>(null);
  useEffect(() => { void eventsApi.get(id).then((item) => { setEvent(item); setForm({ title: item.title, description: item.description, url: item.url, organizer: item.organizer, format: item.format, difficulty: item.difficulty, startDate: item.startDate, endDate: item.endDate, city: item.city, region: item.regionId, lat: item.lat, lng: item.lng, tags: item.tags.join(', ') }); }).catch(() => onNavigate('/404')); }, [id, onNavigate]);
  const set = <K extends keyof EventUpdate>(key: K, value: EventUpdate[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!form) return; setLoading(true); setNotice(null); try { const updated = await eventsApi.update(id, form); setEvent(updated); setNotice({ kind: 'success', text: 'Изменения синхронизированы с event node.' }); } catch (reason) { setNotice({ kind: 'error', text: (reason as ApiError).message || 'Не удалось сохранить данные.' }); } finally { setLoading(false); } };
  if (!event || !form) return <LoadingPanel label="READING EVENT NODE" />;
  return <><PageHeader code={`ADMIN / EVENTS / ${event.id.toUpperCase()}`} title="Edit event node" description="Изменение оперативных данных соревнования." actions={<StatusIndicator status={event.status} />} />
    <form className="edit-form" onSubmit={save}>{notice && <InlineNotice kind={notice.kind}>{notice.text}</InlineNotice>}
      <FormSection code="01" title="Basic information"><Field label="EVENT TITLE"><input value={form.title} onChange={(e) => set('title', e.target.value)} required /></Field><Field label="ORGANIZER"><input value={form.organizer} onChange={(e) => set('organizer', e.target.value)} required /></Field><Field label="DESCRIPTION" wide><textarea rows={4} value={form.description} onChange={(e) => set('description', e.target.value)} required /></Field></FormSection>
      <FormSection code="02" title="Location"><Field label="CITY"><input value={form.city} onChange={(e) => set('city', e.target.value)} /></Field><Field label="REGION CODE"><input value={form.region} onChange={(e) => set('region', e.target.value)} /></Field><Field label="LATITUDE"><input type="number" step="any" value={form.lat} onChange={(e) => set('lat', Number(e.target.value))} /></Field><Field label="LONGITUDE"><input type="number" step="any" value={form.lng} onChange={(e) => set('lng', Number(e.target.value))} /></Field></FormSection>
      <FormSection code="03" title="Schedule & classification"><Field label="START DATE"><input type="date" value={form.startDate} onChange={(e) => set('startDate', e.target.value)} /></Field><Field label="END DATE"><input type="date" value={form.endDate} onChange={(e) => set('endDate', e.target.value)} /></Field><Field label="FORMAT"><select value={form.format} onChange={(e) => set('format', e.target.value as EventUpdate['format'])}><option value="online">ONLINE</option><option value="offline">OFFLINE</option><option value="hybrid">HYBRID</option></select></Field><Field label="DIFFICULTY"><select value={form.difficulty} onChange={(e) => set('difficulty', e.target.value as EventUpdate['difficulty'])}><option>Начальный</option><option>Средний</option><option>Высокий</option><option>Экспертный</option></select></Field></FormSection>
      <FormSection code="04" title="External links"><Field label="OFFICIAL URL"><input type="url" value={form.url} onChange={(e) => set('url', e.target.value)} /></Field><Field label="TAGS"><input value={form.tags} onChange={(e) => set('tags', e.target.value)} placeholder="Web, Pwn, Team" /></Field></FormSection>
      <footer className="form-actions"><button type="button" className="button admin-button" onClick={() => onNavigate('/admin/events')}>CANCEL</button><button className="button admin-button admin-button--primary" disabled={loading}>{loading ? 'SAVING...' : 'SAVE CHANGES'} →</button></footer>
    </form></>;
}
function FormSection({ code, title, children }: { code: string; title: string; children: React.ReactNode }) { return <section className="form-section"><header><span>{code}</span><h2>{title}</h2></header><div className="form-grid">{children}</div></section>; }
function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`field ${wide ? 'field--wide' : ''}`}><span>{label}</span>{children}</label>; }

